manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: karnadii
      url-base: https://github.com/karnadii/
  projects:
    - name: zmk
      remote: karnadii
      revision: zmk-config-shabrina
      import: app/west.yml
  self:
    path: config